---

#- name: "Add vbernat repository"
#  apt_repository:
#    repo: 'ppa:vbernat/haproxy-1.5'
#    state: present
#  tags:
#    - haproxy

- name: "Install haproxy 'Debian'"
  apt:
    pkg: 'haproxy'
    state: latest
  tags:
    - haproxy

- name: "Install state haproxy 'ENABLED=1' to init script"
  lineinfile:
    dest: '/etc/default/haproxy'
    state: present
    regexp: '^#?ENABLED'
    line: 'ENABLED=1'
  notify:
    - restart haproxy
  tags:
    - haproxy

- name: "Create haproxy.conf to rsyslog.d"
  template:
    src: '49-haproxy.conf.j2'
    dest: '/etc/rsyslog.d/49-haproxy.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - restart rsyslog
  tags:
    - haproxy
