---

- name: "Install haproxy 'Debian'"
  apt:
    pkg: "haproxy"
    state: present
  when: "ansible_os_family == 'Debian'"
  tags:
    - haproxy

- name: "Install haproxy 'RedHat'"
  yum:
    name: "haproxy"
    state: present
  when: "ansible_os_family == 'RedHat'"
  tags:
    - haproxy

- name: Upload haproxy.cfg
  template:
    src: "haproxy.conf.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    backup: no
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart haproxy
  tags:
    - haproxy

- name: Install state haproxy "ENABLED=1" to init script
  lineinfile:
    dest: "/etc/default/haproxy"
    state: present
    regexp: "^#?ENABLED"
    line: "ENABLED=1"
  notify:
    - restart haproxy
  when: "ansible_os_family == 'Debian'"
  tags:
    - haproxy

#- name: "Register and start service haproxy"
#  service:
#    name: "haproxy"
#    enabled: yes
#    state: started
#  tags:
#    - haproxy